# Setup
title:               Analysis Again
tagline:             'Tech Blog'
description:         'Tech blog by <a href="https://twitter.com/Joseph7ee" target="_blank">@Joseph7ee</a>.'
url:                 https://joseph7ee.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Joseph Lee
  url:               https://twitter.com/JosephLee
  email:             inyong7ee@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
